autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
    files:
      - '*.go'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/enh\/.+/'
      - '/enhancement\/.+/'
      - '/feat\/.+/'
      - '/feature\/.+/'
    title:
      - '/feat/i'
  - label: 'dependencies'
    files:
      - 'go.mod'
      - 'go.sum'
      - 'vendor*'
    branch:
      - '/deps\/.+/'
template: "not used, but required"
