// Code generated by counterfeiter. DO NOT EDIT.
package filefakes

import (
	"context"
	"sync"

	v1 "github.com/nginx/agent/v3/api/grpc/mpi/v1"
)

type FakeFileServiceOperatorInterface struct {
	ChunkedFileStub        func(context.Context, *v1.File, string, string) error
	chunkedFileMutex       sync.RWMutex
	chunkedFileArgsForCall []struct {
		arg1 context.Context
		arg2 *v1.File
		arg3 string
		arg4 string
	}
	chunkedFileReturns struct {
		result1 error
	}
	chunkedFileReturnsOnCall map[int]struct {
		result1 error
	}
	FileStub        func(context.Context, *v1.File, string, string) error
	fileMutex       sync.RWMutex
	fileArgsForCall []struct {
		arg1 context.Context
		arg2 *v1.File
		arg3 string
		arg4 string
	}
	fileReturns struct {
		result1 error
	}
	fileReturnsOnCall map[int]struct {
		result1 error
	}
	IsConnectedStub        func() bool
	isConnectedMutex       sync.RWMutex
	isConnectedArgsForCall []struct {
	}
	isConnectedReturns struct {
		result1 bool
	}
	isConnectedReturnsOnCall map[int]struct {
		result1 bool
	}
	RenameFileStub        func(context.Context, string, string) error
	renameFileMutex       sync.RWMutex
	renameFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	renameFileReturns struct {
		result1 error
	}
	renameFileReturnsOnCall map[int]struct {
		result1 error
	}
	SetIsConnectedStub        func(bool)
	setIsConnectedMutex       sync.RWMutex
	setIsConnectedArgsForCall []struct {
		arg1 bool
	}
	UpdateClientStub        func(context.Context, v1.FileServiceClient)
	updateClientMutex       sync.RWMutex
	updateClientArgsForCall []struct {
		arg1 context.Context
		arg2 v1.FileServiceClient
	}
	UpdateFileStub        func(context.Context, string, *v1.File) error
	updateFileMutex       sync.RWMutex
	updateFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 *v1.File
	}
	updateFileReturns struct {
		result1 error
	}
	updateFileReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateOverviewStub        func(context.Context, string, []*v1.File, string, int) error
	updateOverviewMutex       sync.RWMutex
	updateOverviewArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []*v1.File
		arg4 string
		arg5 int
	}
	updateOverviewReturns struct {
		result1 error
	}
	updateOverviewReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateFileHashStub        func(context.Context, string, string) error
	validateFileHashMutex       sync.RWMutex
	validateFileHashArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	validateFileHashReturns struct {
		result1 error
	}
	validateFileHashReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFileServiceOperatorInterface) ChunkedFile(arg1 context.Context, arg2 *v1.File, arg3 string, arg4 string) error {
	fake.chunkedFileMutex.Lock()
	ret, specificReturn := fake.chunkedFileReturnsOnCall[len(fake.chunkedFileArgsForCall)]
	fake.chunkedFileArgsForCall = append(fake.chunkedFileArgsForCall, struct {
		arg1 context.Context
		arg2 *v1.File
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.ChunkedFileStub
	fakeReturns := fake.chunkedFileReturns
	fake.recordInvocation("ChunkedFile", []interface{}{arg1, arg2, arg3, arg4})
	fake.chunkedFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFileServiceOperatorInterface) ChunkedFileCallCount() int {
	fake.chunkedFileMutex.RLock()
	defer fake.chunkedFileMutex.RUnlock()
	return len(fake.chunkedFileArgsForCall)
}

func (fake *FakeFileServiceOperatorInterface) ChunkedFileCalls(stub func(context.Context, *v1.File, string, string) error) {
	fake.chunkedFileMutex.Lock()
	defer fake.chunkedFileMutex.Unlock()
	fake.ChunkedFileStub = stub
}

func (fake *FakeFileServiceOperatorInterface) ChunkedFileArgsForCall(i int) (context.Context, *v1.File, string, string) {
	fake.chunkedFileMutex.RLock()
	defer fake.chunkedFileMutex.RUnlock()
	argsForCall := fake.chunkedFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeFileServiceOperatorInterface) ChunkedFileReturns(result1 error) {
	fake.chunkedFileMutex.Lock()
	defer fake.chunkedFileMutex.Unlock()
	fake.ChunkedFileStub = nil
	fake.chunkedFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) ChunkedFileReturnsOnCall(i int, result1 error) {
	fake.chunkedFileMutex.Lock()
	defer fake.chunkedFileMutex.Unlock()
	fake.ChunkedFileStub = nil
	if fake.chunkedFileReturnsOnCall == nil {
		fake.chunkedFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.chunkedFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) File(arg1 context.Context, arg2 *v1.File, arg3 string, arg4 string) error {
	fake.fileMutex.Lock()
	ret, specificReturn := fake.fileReturnsOnCall[len(fake.fileArgsForCall)]
	fake.fileArgsForCall = append(fake.fileArgsForCall, struct {
		arg1 context.Context
		arg2 *v1.File
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.FileStub
	fakeReturns := fake.fileReturns
	fake.recordInvocation("File", []interface{}{arg1, arg2, arg3, arg4})
	fake.fileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFileServiceOperatorInterface) FileCallCount() int {
	fake.fileMutex.RLock()
	defer fake.fileMutex.RUnlock()
	return len(fake.fileArgsForCall)
}

func (fake *FakeFileServiceOperatorInterface) FileCalls(stub func(context.Context, *v1.File, string, string) error) {
	fake.fileMutex.Lock()
	defer fake.fileMutex.Unlock()
	fake.FileStub = stub
}

func (fake *FakeFileServiceOperatorInterface) FileArgsForCall(i int) (context.Context, *v1.File, string, string) {
	fake.fileMutex.RLock()
	defer fake.fileMutex.RUnlock()
	argsForCall := fake.fileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeFileServiceOperatorInterface) FileReturns(result1 error) {
	fake.fileMutex.Lock()
	defer fake.fileMutex.Unlock()
	fake.FileStub = nil
	fake.fileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) FileReturnsOnCall(i int, result1 error) {
	fake.fileMutex.Lock()
	defer fake.fileMutex.Unlock()
	fake.FileStub = nil
	if fake.fileReturnsOnCall == nil {
		fake.fileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) IsConnected() bool {
	fake.isConnectedMutex.Lock()
	ret, specificReturn := fake.isConnectedReturnsOnCall[len(fake.isConnectedArgsForCall)]
	fake.isConnectedArgsForCall = append(fake.isConnectedArgsForCall, struct {
	}{})
	stub := fake.IsConnectedStub
	fakeReturns := fake.isConnectedReturns
	fake.recordInvocation("IsConnected", []interface{}{})
	fake.isConnectedMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFileServiceOperatorInterface) IsConnectedCallCount() int {
	fake.isConnectedMutex.RLock()
	defer fake.isConnectedMutex.RUnlock()
	return len(fake.isConnectedArgsForCall)
}

func (fake *FakeFileServiceOperatorInterface) IsConnectedCalls(stub func() bool) {
	fake.isConnectedMutex.Lock()
	defer fake.isConnectedMutex.Unlock()
	fake.IsConnectedStub = stub
}

func (fake *FakeFileServiceOperatorInterface) IsConnectedReturns(result1 bool) {
	fake.isConnectedMutex.Lock()
	defer fake.isConnectedMutex.Unlock()
	fake.IsConnectedStub = nil
	fake.isConnectedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) IsConnectedReturnsOnCall(i int, result1 bool) {
	fake.isConnectedMutex.Lock()
	defer fake.isConnectedMutex.Unlock()
	fake.IsConnectedStub = nil
	if fake.isConnectedReturnsOnCall == nil {
		fake.isConnectedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isConnectedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) RenameFile(arg1 context.Context, arg2 string, arg3 string) error {
	fake.renameFileMutex.Lock()
	ret, specificReturn := fake.renameFileReturnsOnCall[len(fake.renameFileArgsForCall)]
	fake.renameFileArgsForCall = append(fake.renameFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.RenameFileStub
	fakeReturns := fake.renameFileReturns
	fake.recordInvocation("RenameFile", []interface{}{arg1, arg2, arg3})
	fake.renameFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFileServiceOperatorInterface) RenameFileCallCount() int {
	fake.renameFileMutex.RLock()
	defer fake.renameFileMutex.RUnlock()
	return len(fake.renameFileArgsForCall)
}

func (fake *FakeFileServiceOperatorInterface) RenameFileCalls(stub func(context.Context, string, string) error) {
	fake.renameFileMutex.Lock()
	defer fake.renameFileMutex.Unlock()
	fake.RenameFileStub = stub
}

func (fake *FakeFileServiceOperatorInterface) RenameFileArgsForCall(i int) (context.Context, string, string) {
	fake.renameFileMutex.RLock()
	defer fake.renameFileMutex.RUnlock()
	argsForCall := fake.renameFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeFileServiceOperatorInterface) RenameFileReturns(result1 error) {
	fake.renameFileMutex.Lock()
	defer fake.renameFileMutex.Unlock()
	fake.RenameFileStub = nil
	fake.renameFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) RenameFileReturnsOnCall(i int, result1 error) {
	fake.renameFileMutex.Lock()
	defer fake.renameFileMutex.Unlock()
	fake.RenameFileStub = nil
	if fake.renameFileReturnsOnCall == nil {
		fake.renameFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.renameFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) SetIsConnected(arg1 bool) {
	fake.setIsConnectedMutex.Lock()
	fake.setIsConnectedArgsForCall = append(fake.setIsConnectedArgsForCall, struct {
		arg1 bool
	}{arg1})
	stub := fake.SetIsConnectedStub
	fake.recordInvocation("SetIsConnected", []interface{}{arg1})
	fake.setIsConnectedMutex.Unlock()
	if stub != nil {
		fake.SetIsConnectedStub(arg1)
	}
}

func (fake *FakeFileServiceOperatorInterface) SetIsConnectedCallCount() int {
	fake.setIsConnectedMutex.RLock()
	defer fake.setIsConnectedMutex.RUnlock()
	return len(fake.setIsConnectedArgsForCall)
}

func (fake *FakeFileServiceOperatorInterface) SetIsConnectedCalls(stub func(bool)) {
	fake.setIsConnectedMutex.Lock()
	defer fake.setIsConnectedMutex.Unlock()
	fake.SetIsConnectedStub = stub
}

func (fake *FakeFileServiceOperatorInterface) SetIsConnectedArgsForCall(i int) bool {
	fake.setIsConnectedMutex.RLock()
	defer fake.setIsConnectedMutex.RUnlock()
	argsForCall := fake.setIsConnectedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFileServiceOperatorInterface) UpdateClient(arg1 context.Context, arg2 v1.FileServiceClient) {
	fake.updateClientMutex.Lock()
	fake.updateClientArgsForCall = append(fake.updateClientArgsForCall, struct {
		arg1 context.Context
		arg2 v1.FileServiceClient
	}{arg1, arg2})
	stub := fake.UpdateClientStub
	fake.recordInvocation("UpdateClient", []interface{}{arg1, arg2})
	fake.updateClientMutex.Unlock()
	if stub != nil {
		fake.UpdateClientStub(arg1, arg2)
	}
}

func (fake *FakeFileServiceOperatorInterface) UpdateClientCallCount() int {
	fake.updateClientMutex.RLock()
	defer fake.updateClientMutex.RUnlock()
	return len(fake.updateClientArgsForCall)
}

func (fake *FakeFileServiceOperatorInterface) UpdateClientCalls(stub func(context.Context, v1.FileServiceClient)) {
	fake.updateClientMutex.Lock()
	defer fake.updateClientMutex.Unlock()
	fake.UpdateClientStub = stub
}

func (fake *FakeFileServiceOperatorInterface) UpdateClientArgsForCall(i int) (context.Context, v1.FileServiceClient) {
	fake.updateClientMutex.RLock()
	defer fake.updateClientMutex.RUnlock()
	argsForCall := fake.updateClientArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFileServiceOperatorInterface) UpdateFile(arg1 context.Context, arg2 string, arg3 *v1.File) error {
	fake.updateFileMutex.Lock()
	ret, specificReturn := fake.updateFileReturnsOnCall[len(fake.updateFileArgsForCall)]
	fake.updateFileArgsForCall = append(fake.updateFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 *v1.File
	}{arg1, arg2, arg3})
	stub := fake.UpdateFileStub
	fakeReturns := fake.updateFileReturns
	fake.recordInvocation("UpdateFile", []interface{}{arg1, arg2, arg3})
	fake.updateFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFileServiceOperatorInterface) UpdateFileCallCount() int {
	fake.updateFileMutex.RLock()
	defer fake.updateFileMutex.RUnlock()
	return len(fake.updateFileArgsForCall)
}

func (fake *FakeFileServiceOperatorInterface) UpdateFileCalls(stub func(context.Context, string, *v1.File) error) {
	fake.updateFileMutex.Lock()
	defer fake.updateFileMutex.Unlock()
	fake.UpdateFileStub = stub
}

func (fake *FakeFileServiceOperatorInterface) UpdateFileArgsForCall(i int) (context.Context, string, *v1.File) {
	fake.updateFileMutex.RLock()
	defer fake.updateFileMutex.RUnlock()
	argsForCall := fake.updateFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeFileServiceOperatorInterface) UpdateFileReturns(result1 error) {
	fake.updateFileMutex.Lock()
	defer fake.updateFileMutex.Unlock()
	fake.UpdateFileStub = nil
	fake.updateFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) UpdateFileReturnsOnCall(i int, result1 error) {
	fake.updateFileMutex.Lock()
	defer fake.updateFileMutex.Unlock()
	fake.UpdateFileStub = nil
	if fake.updateFileReturnsOnCall == nil {
		fake.updateFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) UpdateOverview(arg1 context.Context, arg2 string, arg3 []*v1.File, arg4 string, arg5 int) error {
	var arg3Copy []*v1.File
	if arg3 != nil {
		arg3Copy = make([]*v1.File, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.updateOverviewMutex.Lock()
	ret, specificReturn := fake.updateOverviewReturnsOnCall[len(fake.updateOverviewArgsForCall)]
	fake.updateOverviewArgsForCall = append(fake.updateOverviewArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []*v1.File
		arg4 string
		arg5 int
	}{arg1, arg2, arg3Copy, arg4, arg5})
	stub := fake.UpdateOverviewStub
	fakeReturns := fake.updateOverviewReturns
	fake.recordInvocation("UpdateOverview", []interface{}{arg1, arg2, arg3Copy, arg4, arg5})
	fake.updateOverviewMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFileServiceOperatorInterface) UpdateOverviewCallCount() int {
	fake.updateOverviewMutex.RLock()
	defer fake.updateOverviewMutex.RUnlock()
	return len(fake.updateOverviewArgsForCall)
}

func (fake *FakeFileServiceOperatorInterface) UpdateOverviewCalls(stub func(context.Context, string, []*v1.File, string, int) error) {
	fake.updateOverviewMutex.Lock()
	defer fake.updateOverviewMutex.Unlock()
	fake.UpdateOverviewStub = stub
}

func (fake *FakeFileServiceOperatorInterface) UpdateOverviewArgsForCall(i int) (context.Context, string, []*v1.File, string, int) {
	fake.updateOverviewMutex.RLock()
	defer fake.updateOverviewMutex.RUnlock()
	argsForCall := fake.updateOverviewArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeFileServiceOperatorInterface) UpdateOverviewReturns(result1 error) {
	fake.updateOverviewMutex.Lock()
	defer fake.updateOverviewMutex.Unlock()
	fake.UpdateOverviewStub = nil
	fake.updateOverviewReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) UpdateOverviewReturnsOnCall(i int, result1 error) {
	fake.updateOverviewMutex.Lock()
	defer fake.updateOverviewMutex.Unlock()
	fake.UpdateOverviewStub = nil
	if fake.updateOverviewReturnsOnCall == nil {
		fake.updateOverviewReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateOverviewReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) ValidateFileHash(arg1 context.Context, arg2 string, arg3 string) error {
	fake.validateFileHashMutex.Lock()
	ret, specificReturn := fake.validateFileHashReturnsOnCall[len(fake.validateFileHashArgsForCall)]
	fake.validateFileHashArgsForCall = append(fake.validateFileHashArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ValidateFileHashStub
	fakeReturns := fake.validateFileHashReturns
	fake.recordInvocation("ValidateFileHash", []interface{}{arg1, arg2, arg3})
	fake.validateFileHashMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFileServiceOperatorInterface) ValidateFileHashCallCount() int {
	fake.validateFileHashMutex.RLock()
	defer fake.validateFileHashMutex.RUnlock()
	return len(fake.validateFileHashArgsForCall)
}

func (fake *FakeFileServiceOperatorInterface) ValidateFileHashCalls(stub func(context.Context, string, string) error) {
	fake.validateFileHashMutex.Lock()
	defer fake.validateFileHashMutex.Unlock()
	fake.ValidateFileHashStub = stub
}

func (fake *FakeFileServiceOperatorInterface) ValidateFileHashArgsForCall(i int) (context.Context, string, string) {
	fake.validateFileHashMutex.RLock()
	defer fake.validateFileHashMutex.RUnlock()
	argsForCall := fake.validateFileHashArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeFileServiceOperatorInterface) ValidateFileHashReturns(result1 error) {
	fake.validateFileHashMutex.Lock()
	defer fake.validateFileHashMutex.Unlock()
	fake.ValidateFileHashStub = nil
	fake.validateFileHashReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) ValidateFileHashReturnsOnCall(i int, result1 error) {
	fake.validateFileHashMutex.Lock()
	defer fake.validateFileHashMutex.Unlock()
	fake.ValidateFileHashStub = nil
	if fake.validateFileHashReturnsOnCall == nil {
		fake.validateFileHashReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateFileHashReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFileServiceOperatorInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.chunkedFileMutex.RLock()
	defer fake.chunkedFileMutex.RUnlock()
	fake.fileMutex.RLock()
	defer fake.fileMutex.RUnlock()
	fake.isConnectedMutex.RLock()
	defer fake.isConnectedMutex.RUnlock()
	fake.renameFileMutex.RLock()
	defer fake.renameFileMutex.RUnlock()
	fake.setIsConnectedMutex.RLock()
	defer fake.setIsConnectedMutex.RUnlock()
	fake.updateClientMutex.RLock()
	defer fake.updateClientMutex.RUnlock()
	fake.updateFileMutex.RLock()
	defer fake.updateFileMutex.RUnlock()
	fake.updateOverviewMutex.RLock()
	defer fake.updateOverviewMutex.RUnlock()
	fake.validateFileHashMutex.RLock()
	defer fake.validateFileHashMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFileServiceOperatorInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
