{
 "title": "NGINX Agent",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_cpu_system + system_cpu_user",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_mem_used / system_mem_total * 100",
     "legendFormat": "% memory used"
    }
   ]
  },
  {
   "title": "Swap Free %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "system_swap_pct_free", "legendFormat": "Swap used" }
   ]
  },
  {
   "title": "NGINX",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_status", "legendFormat": "Status" },
    { "expr": "nginx_workers_count", "legendFormat": "Worker Count" }
   ]
  },
  {
   "title": "HTTP requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(nginx_http_request_count[1m]) * 60",
     "legendFormat": "requests / min"
    }
   ]
  },
  {
   "title": "HTTP bytes sent per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "rate(nginx_http_request_bytes_sent[1m]) * 60",
     "legendFormat": "bytes / min"
    }
   ]
  },
  {
   "title": "NGINX HTTP Responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_http_status_1xx", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_http_status_2xx", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_http_status_3xx", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_http_status_4xx", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_http_status_5xx", "legendFormat": "{{__name__}}" },
    {}
   ]
  }
 ]
}