version: "2"
linters:
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - dupl
    - decorder
    - errorlint
    - exhaustive
    - forcetypeassert
    - funcorder
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gosec
    - grouper
    - importas
    - inamedparam
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
#    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usetesting
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    cyclop:
      max-complexity: 10
      package-average: 0
    errorlint:
      errorf: true
      errorf-multi: false
      asserts: false
      comparison: false
    gocognit:
      min-complexity: 20
    goconst:
      match-constant: true
      min-len: 2
      min-occurrences: 3
      numbers: false
      min: 3
      max: 3
      ignore-calls: true
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        elseif:
          skipBalanced: true
        ifElseChain:
          minThreshold: 4
    gocyclo:
      min-complexity: 20
    godox:
      keywords:
        - TODO
        - BUG
        - FIXME
        - HACK
    goheader:
      template: |-
        Copyright (c) F5, Inc.

        This source code is licensed under the Apache License, Version 2.0 license found in the
        LICENSE file in the root directory of this source tree.
    gomoddirectives:
      replace-local: false
      exclude-forbidden: false
      retract-allow-no-explanation: false
    gosec:
      includes:
        - G101
        - G102
        - G103
        - G104
        - G106
        - G107
        - G108
        - G109
        - G110
        - G111
        - G112
        - G113
        - G114
        - G201
        - G202
        - G203
        - G204
        - G301
        - G302
        - G303
        - G304
        - G305
        - G306
        - G307
        - G401
        - G402
        - G403
        - G404
        - G501
        - G502
        - G503
        - G504
        - G505
        - G602
      severity: low
      confidence: medium
      config:
        G101:
          entropy_threshold: "80.0"
          ignore_entropy: false
          pattern: (?i)passwd|pass|password|pwd|secret|token|pw|apiKey|bearer|cred
          per_char_threshold: "3.0"
          truncate: "16"
        G111:
          pattern: http\.Dir\("\/"\)|http\.Dir\('\/'\)
        G301: "0750"
        G302: "0600"
        G306: "0600"
        global:
          '#nosec': ""
          audit: false
          nosec: false
          show-ignored: false
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    grouper:
      const-require-single-const: false
      const-require-grouping: false
      import-require-single-import: false
      import-require-grouping: false
      type-require-single-type: false
      type-require-grouping: false
      var-require-single-var: false
      var-require-grouping: false
    importas:
      alias:
        - pkg: go.opentelemetry.io/otel/sdk/metric
          alias: metricSdk
      no-unaliased: true
      no-extra-aliases: false
    interfacebloat:
      max: 10
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - google.golang.org/grpc/credentials
        - github.com/testcontainers/testcontainers-go
        - google.golang.org/grpc
    lll:
      line-length: 120
      tab-width: 4
    maintidx:
      under: 20
    makezero:
      always: false
    misspell:
      locale: US
    nakedret:
      max-func-lines: 31
    nestif:
      min-complexity: 5
    nilnil:
      checked-types:
        - ptr
        - func
        - iface
        - map
        - chan
    nlreturn:
      block-size: 2
#    nolintlint:
#      # Disable to ensure that all nolint directives actually have an effect.
#      # Default: false
#      allow-unused: true
#      # Exclude following linters from requiring an explanation.
#      # Default: []
#      allow-no-explanation: [ ]
#      # Enable to require an explanation of nonzero length after each nolint directive.
#      # Default: false
#      require-explanation: true
#      # Enable to require nolint directives to mention the specific linter being suppressed.
#      # Default: false
#      require-specific: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      qualified-name: false
    promlinter:
      strict: false
    reassign:
      patterns:
        - Err.*
        - EOF
    revive:
      max-open-files: 2048
      confidence: 0.8
      severity: warning
      enable-all-rules: false
      rules:
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2
              allowStrs: '""'
              ignoreFuncs: host\.*
              maxLitCount: "3"
          severity: warning
          disabled: true
        - name: argument-limit
          arguments:
            - 5
          severity: warning
          disabled: false
        - name: atomic
          severity: warning
          disabled: false
        - name: banned-characters
          arguments:
            - Ω
            - Σ
            - σ
          severity: warning
          disabled: false
        - name: bare-return
          severity: warning
          disabled: false
        - name: blank-imports
          severity: warning
          disabled: false
        - name: bool-literal-in-expr
          severity: warning
          disabled: false
        - name: call-to-gc
          severity: warning
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 10
          severity: warning
          disabled: false
        - name: comment-spacings
          severity: warning
          disabled: true
        - name: confusing-naming
          severity: warning
          disabled: false
        - name: confusing-results
          severity: warning
          disabled: false
        - name: constant-logical-expr
          severity: warning
          disabled: false
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
          severity: warning
          disabled: false
        - name: context-keys-type
          severity: warning
          disabled: false
        - name: cyclomatic
          arguments:
            - 10
          severity: warning
          disabled: false
        - name: datarace
          severity: warning
          disabled: false
        - name: deep-exit
          severity: warning
          disabled: false
        - name: defer
          arguments:
            - - call-chain
              - loop
          severity: warning
          disabled: false
        - name: dot-imports
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: early-return
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: empty-block
          severity: warning
          disabled: false
        - name: empty-lines
          severity: warning
          disabled: false
        - name: enforce-map-style
          arguments:
            - make
          severity: warning
          disabled: false
        - name: error-naming
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: errorf
          severity: warning
          disabled: false
        - name: flag-parameter
          severity: warning
          disabled: false
        - name: function-result-limit
          arguments:
            - 3
          severity: warning
          disabled: false
        - name: get-return
          severity: warning
          disabled: false
        - name: identical-branches
          severity: warning
          disabled: false
        - name: if-return
          severity: warning
          disabled: false
        - name: increment-decrement
          severity: warning
          disabled: false
        - name: indent-error-flow
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: import-alias-naming
          arguments:
            - ^[a-z][a-zA-Z0-9]{0,}$
          severity: warning
          disabled: false
        - name: imports-blocklist
          arguments:
            - crypto/md5
            - crypto/sha1
          severity: warning
          disabled: false
        - name: import-shadowing
          severity: warning
          disabled: false
        - name: max-public-structs
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: modifies-parameter
          severity: warning
          disabled: false
        - name: modifies-value-receiver
          severity: warning
          disabled: false
        - name: nested-structs
          severity: warning
          disabled: false
        - name: optimize-operands-order
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: false
        - name: range
          severity: warning
          disabled: false
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: range-val-address
          severity: warning
          disabled: false
        - name: receiver-naming
          severity: warning
          disabled: false
        - name: redundant-import-alias
          severity: warning
          disabled: false
        - name: redefines-builtin-id
          severity: warning
          disabled: false
        - name: string-of-int
          severity: warning
          disabled: false
        - name: string-format
          arguments:
            - - core.WriteError[1].Message
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /(^|[^\.!?])$/
              - must not end in punctuation
            - - panic
              - /^[^\n]*$/
              - must not contain line breaks
          severity: warning
          disabled: true
        - name: struct-tag
          arguments:
            - json,inline
            - bson,outline,gnu
          severity: warning
          disabled: false
        - name: superfluous-else
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: time-equal
          severity: warning
          disabled: false
        - name: time-naming
          severity: warning
          disabled: false
        - name: var-naming
          arguments:
            - - ID
            - - VM
            - - upperCaseConst: true
          severity: warning
          disabled: true
        - name: var-declaration
          severity: warning
          disabled: false
        - name: unconditional-recursion
          severity: warning
          disabled: false
        - name: unexported-naming
          severity: warning
          disabled: false
        - name: unexported-return
          severity: warning
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - myFunction
          severity: warning
          disabled: true
        - name: unnecessary-stmt
          severity: warning
          disabled: false
        - name: unreachable-code
          severity: warning
          disabled: false
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: true
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: true
        - name: useless-break
          severity: warning
          disabled: false
        - name: waitgroup-by-value
          severity: warning
          disabled: false
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    sloglint:
      no-mixed-args: true
      kv-only: false
      attr-only: false
      context: "scope"
      static-msg: false
      no-raw-keys: false
      key-naming-case: snake
      args-on-sep-lines: false
    tagalign:
      align: true
      sort: true
      order:
        - json
        - yaml
        - yml
        - toml
        - mapstructure
        - binding
        - validate
      strict: false
    testifylint:
      enable-all: true
      suite-extra-assert-call:
        mode: remove
    thelper:
      test:
        first: true
        name: false
        begin: true
      fuzz:
        first: true
        name: false
        begin: true
      benchmark:
        first: true
        name: false
        begin: true
      tb:
        first: true
        name: false
        begin: true
    unparam:
      check-exported: true
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: true
      exported-fields-are-used: false
      parameters-are-used: true
      local-variables-are-used: false
      generated-is-used: true
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - goconst
        path: (.+)_test\.go
    paths:
      - .*gen.go
      - .pb.go
      - .pb.validate.go
      - .*/generated_[A-Za-z_]*\.go
      - .*fakes
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/nginx/agent)
        - blank
        - dot
      custom-order: true
    gofumpt:
      module-path: github.com/nginx/agent
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - .*gen.go
      - .pb.go
      - .pb.validate.go
      - .*/generated_[A-Za-z_]*\.go
      - .*fakes
      - third_party$
      - builtin$
      - examples$
