# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: (^site/vendor/|.*pb2.*)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '(\.md$)'
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-vcs-permalinks
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: fix-byte-order-marker
      - id: detect-private-key
        exclude: ^(examples/|tests/)

  - repo: local
    hooks:
      - id: golang-diff
        name: create-go-diff
        entry: bash -c 'git diff -p origin/main > /tmp/diff.patch'
        language: system
        types: [go]
        pass_filenames: false

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.2
    hooks:
      - id: golangci-lint
        args: [--new-from-patch=/tmp/diff.patch]

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
    - id: markdownlint-cli2

ci:
  skip: [golang-diff, golangci-lint, check-jsonschema, markdownlint-cli2]
