BUF                = "github.com/bufbuild/buf/cmd/buf@v1.29.0"
OAPI_CODEGEN       = "github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@v2.0.0"
LEFTHOOK           = "github.com/evilmartians/lefthook@v1.5.5"
GO_SWAGGER         = "github.com/go-swagger/go-swagger/cmd/swagger"
PROTOBUF           = "github.com/gogo/protobuf/protoc-gen-gogo"
GOLANGCI_LINT      = "github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2"
PROTOC_GENGO       = "google.golang.org/protobuf/cmd/protoc-gen-go@v1.32.0"
PROTOC_FAST        = "github.com/gogo/protobuf/protoc-gen-gogofast"
PROTOC_VALIDATORS  = "github.com/mwitkow/go-proto-validators/protoc-gen-govalidators"
PROTOC_GEN_DOC     = "github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc"
PROTOC_GEN_GO_GRPC = "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
NFPM               = "github.com/goreleaser/nfpm/v2/cmd/nfpm"
MOCKGEN            = "go.uber.org/mock/mockgen"
GOFUMPT	           = "mvdan.cc/gofumpt@v0.6.0"
COUNTERFEITER      = "github.com/maxbrunsfeld/counterfeiter/v6@v6.7.0"

install-tools: ## Install tool dependencies
	@echo "Installing Tools"
	@$(GOGET) $(BUF)
	@$(GOGET) $(OAPI_CODEGEN)
	@$(GOGET) $(LEFTHOOK)
	@$(GOGET) $(GO_SWAGGER)
	@$(GOGET) $(PROTOBUF)
	@$(GOGET) $(GOLANGCI_LINT)
	@$(GOGET) $(PROTOC_GENGO)
	@$(GOGET) $(PROTOC_FAST)
	@$(GOGET) $(PROTOC_VALIDATORS)
	@$(GOGET) $(PROTOC_GEN_DOC)
	@$(GOGET) $(PROTOC_GEN_GO_GRPC)
	@$(GOGET) $(NFPM)
	@$(GOGET) $(MOCKGEN)
	@$(GOGET) $(GOFUMPT)
	@$(GOGET) $(COUNTERFEITER)
	@$(GORUN) $(LEFTHOOK) install pre-push
