openapi: 3.0.2
info:
  title: DataPlane API
  version: 1.0.0
paths:
  /instances:
    get:
      summary: Returns a list of instances.
      responses:
        '200':
          description: A JSON array of instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Instance'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /instances/{instanceId}/configurations:
    put:
      summary: Update an instance's configuration.
      operationId: UpdateInstanceConfiguration
      parameters:
        - name: instanceId
          in: path
          description: ID of instance
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
      responses:
        '200':
          description: A instance's configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorrelationId'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /instances/{instanceId}/configurations/status:
    get:
      summary: Returns the latest status of the instance's configuration
      operationId: GetInstanceConfigurationStatus
      parameters:
        - name: instanceId
          in: path
          description: ID of instance
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Configuration status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigurationStatus'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    NginxMeta:
      type: object
      required:
        - type
      properties:
        type:
          $ref: "#/components/schemas/MetaType"
        conf_path:
          type: string
        exe_path:
          type: string
    Instance:
      type: object
      properties:
        instanceId:
          type: string
          example: "aecea348-62c1-4e3d-b848-6d6cdeb1cb9c"
        type:
          $ref: "#/components/schemas/InstanceType"
          example: NGINXPLUS
        version:
          type: string
          example: "nginx/1.25.1"
        meta:
          type: object
          oneOf:
            - $ref: "#/components/schemas/NginxMeta"
          discriminator:
            propertyName: type
    InstanceType:
      type: string
      description: "The type of a data plane instance"
      enum:
        - SYSTEM
        - CUSTOM
        - NGINX
        - NGINXPLUS
        - AGENT
        - UNIT
        - NIC
        - NGF
    MetaType:
      type: string
      description: "The type of metadata"
      enum:
        - NGINX_META
    Configuration:
      type: object
      properties:
        location:
          type: string
          example: "https://file-server.com/aecea348-62c1-4e3d-b848-6d6cdeb1cb9c"
    ConfigurationStatus:
      type: object
      properties:
        correlationId:
          type: string
          example: "9e2d49c9-ada2-4ed1-b6f2-391d5cf634d9"
        lastUpdated:
          type: string
          format: date-time
          example: "2023-10-19T11:26:32.676Z"
        status:
          $ref: "#/components/schemas/ConfigurationStatusType"
          example: SUCCESS
        message:
          type: string
          example: "Config updated successfully"
    ConfigurationStatusType:
      type: string
      description: "The type of configuration status"
      enum:
        - IN_PROGESS
        - SUCCESS
        - FAILED
        - ROLLBACK_FAILED
    CorrelationId:
      type: object
      properties:
        correlationId:
          type: string
          example: "9e2d49c9-ada2-4ed1-b6f2-391d5cf634d9"
