openapi: 3.0.2
info:
  title: Dataplane API
  version: 1.0.0
paths:
  /instances:
    get:
      summary: Returns a list of instances.
      responses:
        '200':
          description: A JSON array of instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../common/common.yaml#/components/schemas/Instance'
        '500':
          $ref: '../common/common.yaml#/components/responses/InternalServerError'
  /instances/{instanceId}/configurations:
    put:
      summary: Update an instance's configuration.
      operationId: UpdateInstanceConfiguration
      parameters:
        - name: instanceId
          in: path
          description: ID of instance
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
      responses:
        '200':
          description: A instance's configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorrelationId'
        '404':
          $ref: '../common/common.yaml#/components/responses/NotFound'
        '500':
          $ref: '../common/common.yaml#/components/responses/InternalServerError'

components:
  schemas:
    Configuration:
      type: object
      properties:
        location:
          type: string
          example: "https://file-server.com/aecea348-62c1-4e3d-b848-6d6cdeb1cb9c"
    CorrelationId:
      type: object
      properties:
        correlationId:
          type: string
          example: "9e2d49c9-ada2-4ed1-b6f2-391d5cf634d9"
