name: configure-goproxy
author: s.breen
description: Sets the current Go module proxy based on the presence of a private proxy URL in secrets
runs:
  using: 'composite'
  steps:
    - name: Configure Go Proxy
      id: configure-goproxy
      shell: bash
      run: |
        if [[ "${{ secrets.ARTIFACTORY_USER }}" == "" ]] || 
        [[ ${{ github.event.pull_request.head.repo.fork }} ]] ||
        [[ ${{ startsWith(github.head_ref, 'dependabot-')}} ]] ; then
          echo "No Artifactory secrets available - using direct GOPROXY"
          GOPROXY_VALUE="direct"
        else
          echo "Development mode - using dev Artifactory"
          GOPROXY_VALUE="https://${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_TOKEN }}@${{ secrets.ARTIFACTORY_URL }}"
        fi
        echo "GOPROXY=${GOPROXY_VALUE}" >> $GITHUB_ENV
    
