name: configure-goproxy
author: s.breen
description: Sets the current Go module proxy based on the presence of a private proxy URL in secrets
runs:
  using: 'composite'
  steps:
    - name: Configure Go Proxy
      id: configure-goproxy
      shell: bash
      run: |
        if [[ "${{ secrets.ARTIFACTORY_USER }}" == "" ]]; then
        echo "No Artifactory secrets available - using direct GOPROXY"
        GOPROXY_VALUE="direct"
        elif [[ "${{ inputs.is_production_release }}" == "true" ]] || [[ ("${{ github.event_name }}" == "push" || "${{ github.event_name }}" == "schedule") && ("${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" =~ ^refs/heads/release-) ]]; then
        echo "Production mode - using production Artifactory"
        GOPROXY_VALUE="https://${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_TOKEN }}@${{ secrets.ARTIFACTORY_ENDPOINT }}"
        else
        echo "Development mode - using dev Artifactory"
        GOPROXY_VALUE="https://${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_TOKEN }}@${{ secrets.ARTIFACTORY_DEV_ENDPOINT }}"
        fi
        echo "GOPROXY=${GOPROXY_VALUE}" >> $GITHUB_ENV
    
