openapi: 3.0.2
info:
  title: NGINX Link Common Components
  description: Schemas for common entities in NGINX Link's APIs
  version: 0.0.1
security:
  - Bearer: []
paths: {}
components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    AgentMeta:
      type: object
      required:
        - type
      properties:
        type:
          $ref: "#/components/schemas/MetaType"
        config:
          type: string
        metrics:
          type: string
        registration:
          type: string
    NginxMeta:
      type: object
      required:
        - type
      properties:
        type:
          $ref: "#/components/schemas/MetaType"
        loadable_modules:
          type: string
        runnable_modules:
          type: string
    Instance:
      type: object
      properties:
        instanceId:
          type: string
          example: "aecea348-62c1-4e3d-b848-6d6cdeb1cb9c"
        type:
          $ref: "#/components/schemas/InstanceType"
          example: NGINXPLUS
        version:
          type: string
          example: "nginx/1.25.1"
        meta:
          type: object
          oneOf:
            - $ref: "#/components/schemas/NginxMeta"
            - $ref: "#/components/schemas/AgentMeta"
          discriminator:
            propertyName: type
    InstanceType:
      type: string
      description: "The type of a data plane instance"
      enum:
        - SYSTEM
        - CUSTOM
        - NGINX
        - NGINXPLUS
        - AGENT
        - UNIT
        - NIC
        - NGF
    MessageType:
      type: string
      description: "The available message types on the Management and Data plane APIs"
      enum:
        - CONFIG
        - CONFIG_RESPONSE
        - HEARTBEAT
        - ATTACHMENT
        - CERTIFICATE
        - DATAPLANE_REQUEST
        - DATAPLANE_UPDATE
        - CONTROL
        - CONTROL_RESPONSE
        - FILES_RESPONSE
    MetaType:
      type: string
      description: "The type of metadata"
      enum:
        - NGINX_META
        - AGENT_META
