// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNginxHTTPConnectionCountDataPoint(ts, 1, AttributeNginxConnectionsOutcomeACCEPTED)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNginxHTTPConnectionsDataPoint(ts, 1, AttributeNginxConnectionsOutcomeACCEPTED)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNginxHTTPRequestCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNginxHTTPRequestsDataPoint(ts, 1, "nginx.gateway.class-val", "nginx.gateway.name-val", "nginx.gateway.namespace-val", AttributeNginxRouteKindHTTPRoute, "nginx.route.name-val", "nginx.route.namespace-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNginxHTTPResponseCountDataPoint(ts, 1, AttributeNginxStatusRange1xx)

			rb := mb.NewResourceBuilder()
			rb.SetInstanceID("instance.id-val")
			rb.SetInstanceType("instance.type-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "nginx.http.connection.count":
					assert.False(t, validatedMetrics["nginx.http.connection.count"], "Found a duplicate in the metrics slice: nginx.http.connection.count")
					validatedMetrics["nginx.http.connection.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "The current number of connections.", mi.Description())
					assert.Equal(t, "connections", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					nginxConnectionsOutcomeAttrVal, ok := dp.Attributes().Get("nginx.connections.outcome")
					assert.True(t, ok)
					assert.Equal(t, "ACCEPTED", nginxConnectionsOutcomeAttrVal.Str())
				case "nginx.http.connections":
					assert.False(t, validatedMetrics["nginx.http.connections"], "Found a duplicate in the metrics slice: nginx.http.connections")
					validatedMetrics["nginx.http.connections"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "The total number of connections, since NGINX was last started or reloaded.", mi.Description())
					assert.Equal(t, "connections", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					nginxConnectionsOutcomeAttrVal, ok := dp.Attributes().Get("nginx.connections.outcome")
					assert.True(t, ok)
					assert.Equal(t, "ACCEPTED", nginxConnectionsOutcomeAttrVal.Str())
				case "nginx.http.request.count":
					assert.False(t, validatedMetrics["nginx.http.request.count"], "Found a duplicate in the metrics slice: nginx.http.request.count")
					validatedMetrics["nginx.http.request.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "The total number of client requests received, since the last collection interval.", mi.Description())
					assert.Equal(t, "requests", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nginx.http.requests":
					assert.False(t, validatedMetrics["nginx.http.requests"], "Found a duplicate in the metrics slice: nginx.http.requests")
					validatedMetrics["nginx.http.requests"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "The total number of client requests received, since NGINX was last started or reloaded.", mi.Description())
					assert.Equal(t, "requests", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					nginxGatewayClassAttrVal, ok := dp.Attributes().Get("nginx.gateway.class")
					assert.True(t, ok)
					assert.Equal(t, "nginx.gateway.class-val", nginxGatewayClassAttrVal.Str())
					nginxGatewayNameAttrVal, ok := dp.Attributes().Get("nginx.gateway.name")
					assert.True(t, ok)
					assert.Equal(t, "nginx.gateway.name-val", nginxGatewayNameAttrVal.Str())
					nginxGatewayNamespaceAttrVal, ok := dp.Attributes().Get("nginx.gateway.namespace")
					assert.True(t, ok)
					assert.Equal(t, "nginx.gateway.namespace-val", nginxGatewayNamespaceAttrVal.Str())
					nginxRouteKindAttrVal, ok := dp.Attributes().Get("nginx.route.kind")
					assert.True(t, ok)
					assert.Equal(t, "HTTPRoute", nginxRouteKindAttrVal.Str())
					nginxRouteNameAttrVal, ok := dp.Attributes().Get("nginx.route.name")
					assert.True(t, ok)
					assert.Equal(t, "nginx.route.name-val", nginxRouteNameAttrVal.Str())
					nginxRouteNamespaceAttrVal, ok := dp.Attributes().Get("nginx.route.namespace")
					assert.True(t, ok)
					assert.Equal(t, "nginx.route.namespace-val", nginxRouteNamespaceAttrVal.Str())
				case "nginx.http.response.count":
					assert.False(t, validatedMetrics["nginx.http.response.count"], "Found a duplicate in the metrics slice: nginx.http.response.count")
					validatedMetrics["nginx.http.response.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "The total number of HTTP responses since the last collection interval, grouped by status code range.", mi.Description())
					assert.Equal(t, "responses", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					nginxStatusRangeAttrVal, ok := dp.Attributes().Get("nginx.status_range")
					assert.True(t, ok)
					assert.Equal(t, "1xx", nginxStatusRangeAttrVal.Str())
				}
			}
		})
	}
}
