// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Messenger_MessageChannel_FullMethodName = "/f5.nginx.agent.v3.test.Messenger/MessageChannel"
)

// MessengerClient is the client API for Messenger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessengerClient interface {
	// A Bidirectional streaming RPC established by the agent and is kept open
	MessageChannel(ctx context.Context, opts ...grpc.CallOption) (Messenger_MessageChannelClient, error)
}

type messengerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessengerClient(cc grpc.ClientConnInterface) MessengerClient {
	return &messengerClient{cc}
}

func (c *messengerClient) MessageChannel(ctx context.Context, opts ...grpc.CallOption) (Messenger_MessageChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &Messenger_ServiceDesc.Streams[0], Messenger_MessageChannel_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &messengerMessageChannelClient{stream}
	return x, nil
}

type Messenger_MessageChannelClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type messengerMessageChannelClient struct {
	grpc.ClientStream
}

func (x *messengerMessageChannelClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messengerMessageChannelClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessengerServer is the server API for Messenger service.
// All implementations must embed UnimplementedMessengerServer
// for forward compatibility
type MessengerServer interface {
	// A Bidirectional streaming RPC established by the agent and is kept open
	MessageChannel(Messenger_MessageChannelServer) error
	mustEmbedUnimplementedMessengerServer()
}

// UnimplementedMessengerServer must be embedded to have forward compatible implementations.
type UnimplementedMessengerServer struct {
}

func (UnimplementedMessengerServer) MessageChannel(Messenger_MessageChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method MessageChannel not implemented")
}
func (UnimplementedMessengerServer) mustEmbedUnimplementedMessengerServer() {}

// UnsafeMessengerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessengerServer will
// result in compilation errors.
type UnsafeMessengerServer interface {
	mustEmbedUnimplementedMessengerServer()
}

func RegisterMessengerServer(s grpc.ServiceRegistrar, srv MessengerServer) {
	s.RegisterService(&Messenger_ServiceDesc, srv)
}

func _Messenger_MessageChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessengerServer).MessageChannel(&messengerMessageChannelServer{stream})
}

type Messenger_MessageChannelServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type messengerMessageChannelServer struct {
	grpc.ServerStream
}

func (x *messengerMessageChannelServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messengerMessageChannelServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Messenger_ServiceDesc is the grpc.ServiceDesc for Messenger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Messenger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "f5.nginx.agent.v3.test.Messenger",
	HandlerType: (*MessengerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageChannel",
			Handler:       _Messenger_MessageChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}
