name: nginx-agent
description: NGINX Agent
arch: ${ARCH}
version: ${VERSION}
priority: optional
vendor: NGINX Software, Inc.
maintainer: NGINX Inc. <agent@nginx.org>
homepage: https://github.com/nginx/agent
license: Apache 2.0
contents:
  - src: ./build/nginx-agent
    dst: /usr/bin/nginx-agent
  - dst: /etc/nginx-agent
    type: dir
  - src: ./scripts/packages/nginx-agent.service
    dst: /etc/systemd/system/nginx-agent.service
  - src: ./scripts/selinux/nginx_agent_selinux.8.gz
    dst: /usr/share/man/man8/nginx_agent_selinux.8.gz
    packager: rpm
  - src: ./scripts/selinux/nginx_agent.if
    dst: /usr/share/selinux/devel/include/contrib/nginx_agent.if
    packager: rpm
  - src: ./scripts/selinux/nginx_agent.pp
    dst: /usr/share/selinux/packages/nginx_agent.pp
    packager: rpm
  - dst: /var/log/nginx-agent
    type: dir
overrides:
  deb:
    depends:
      - apt-transport-https
scripts:
  preinstall: "./scripts/packages/preinstall.sh"
  postinstall: "./scripts/packages/postinstall.sh"
  preremove: "./scripts/packages/preremove.sh"
  postremove: "./scripts/packages/postremove.sh"
