// Code generated by counterfeiter. DO NOT EDIT.
package execfakes

import (
	"bytes"
	"context"
	"sync"

	v1 "github.com/nginx/agent/v3/api/grpc/mpi/v1"
	"github.com/nginx/agent/v3/internal/datasource/host/exec"
)

type FakeExecInterface struct {
	FindExecutableStub        func(string) (string, error)
	findExecutableMutex       sync.RWMutex
	findExecutableArgsForCall []struct {
		arg1 string
	}
	findExecutableReturns struct {
		result1 string
		result2 error
	}
	findExecutableReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetHostIDStub        func(context.Context) (string, error)
	getHostIDMutex       sync.RWMutex
	getHostIDArgsForCall []struct {
		arg1 context.Context
	}
	getHostIDReturns struct {
		result1 string
		result2 error
	}
	getHostIDReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetHostnameStub        func() (string, error)
	getHostnameMutex       sync.RWMutex
	getHostnameArgsForCall []struct {
	}
	getHostnameReturns struct {
		result1 string
		result2 error
	}
	getHostnameReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetReleaseInfoStub        func(context.Context) *v1.ReleaseInfo
	getReleaseInfoMutex       sync.RWMutex
	getReleaseInfoArgsForCall []struct {
		arg1 context.Context
	}
	getReleaseInfoReturns struct {
		result1 *v1.ReleaseInfo
	}
	getReleaseInfoReturnsOnCall map[int]struct {
		result1 *v1.ReleaseInfo
	}
	KillProcessStub        func(int32) error
	killProcessMutex       sync.RWMutex
	killProcessArgsForCall []struct {
		arg1 int32
	}
	killProcessReturns struct {
		result1 error
	}
	killProcessReturnsOnCall map[int]struct {
		result1 error
	}
	RunCmdStub        func(context.Context, string, ...string) (*bytes.Buffer, error)
	runCmdMutex       sync.RWMutex
	runCmdArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}
	runCmdReturns struct {
		result1 *bytes.Buffer
		result2 error
	}
	runCmdReturnsOnCall map[int]struct {
		result1 *bytes.Buffer
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeExecInterface) FindExecutable(arg1 string) (string, error) {
	fake.findExecutableMutex.Lock()
	ret, specificReturn := fake.findExecutableReturnsOnCall[len(fake.findExecutableArgsForCall)]
	fake.findExecutableArgsForCall = append(fake.findExecutableArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.FindExecutableStub
	fakeReturns := fake.findExecutableReturns
	fake.recordInvocation("FindExecutable", []interface{}{arg1})
	fake.findExecutableMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeExecInterface) FindExecutableCallCount() int {
	fake.findExecutableMutex.RLock()
	defer fake.findExecutableMutex.RUnlock()
	return len(fake.findExecutableArgsForCall)
}

func (fake *FakeExecInterface) FindExecutableCalls(stub func(string) (string, error)) {
	fake.findExecutableMutex.Lock()
	defer fake.findExecutableMutex.Unlock()
	fake.FindExecutableStub = stub
}

func (fake *FakeExecInterface) FindExecutableArgsForCall(i int) string {
	fake.findExecutableMutex.RLock()
	defer fake.findExecutableMutex.RUnlock()
	argsForCall := fake.findExecutableArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeExecInterface) FindExecutableReturns(result1 string, result2 error) {
	fake.findExecutableMutex.Lock()
	defer fake.findExecutableMutex.Unlock()
	fake.FindExecutableStub = nil
	fake.findExecutableReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeExecInterface) FindExecutableReturnsOnCall(i int, result1 string, result2 error) {
	fake.findExecutableMutex.Lock()
	defer fake.findExecutableMutex.Unlock()
	fake.FindExecutableStub = nil
	if fake.findExecutableReturnsOnCall == nil {
		fake.findExecutableReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.findExecutableReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeExecInterface) GetHostID(arg1 context.Context) (string, error) {
	fake.getHostIDMutex.Lock()
	ret, specificReturn := fake.getHostIDReturnsOnCall[len(fake.getHostIDArgsForCall)]
	fake.getHostIDArgsForCall = append(fake.getHostIDArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetHostIDStub
	fakeReturns := fake.getHostIDReturns
	fake.recordInvocation("GetHostID", []interface{}{arg1})
	fake.getHostIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeExecInterface) GetHostIDCallCount() int {
	fake.getHostIDMutex.RLock()
	defer fake.getHostIDMutex.RUnlock()
	return len(fake.getHostIDArgsForCall)
}

func (fake *FakeExecInterface) GetHostIDCalls(stub func(context.Context) (string, error)) {
	fake.getHostIDMutex.Lock()
	defer fake.getHostIDMutex.Unlock()
	fake.GetHostIDStub = stub
}

func (fake *FakeExecInterface) GetHostIDArgsForCall(i int) context.Context {
	fake.getHostIDMutex.RLock()
	defer fake.getHostIDMutex.RUnlock()
	argsForCall := fake.getHostIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeExecInterface) GetHostIDReturns(result1 string, result2 error) {
	fake.getHostIDMutex.Lock()
	defer fake.getHostIDMutex.Unlock()
	fake.GetHostIDStub = nil
	fake.getHostIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeExecInterface) GetHostIDReturnsOnCall(i int, result1 string, result2 error) {
	fake.getHostIDMutex.Lock()
	defer fake.getHostIDMutex.Unlock()
	fake.GetHostIDStub = nil
	if fake.getHostIDReturnsOnCall == nil {
		fake.getHostIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getHostIDReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeExecInterface) GetHostname() (string, error) {
	fake.getHostnameMutex.Lock()
	ret, specificReturn := fake.getHostnameReturnsOnCall[len(fake.getHostnameArgsForCall)]
	fake.getHostnameArgsForCall = append(fake.getHostnameArgsForCall, struct {
	}{})
	stub := fake.GetHostnameStub
	fakeReturns := fake.getHostnameReturns
	fake.recordInvocation("GetHostname", []interface{}{})
	fake.getHostnameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeExecInterface) GetHostnameCallCount() int {
	fake.getHostnameMutex.RLock()
	defer fake.getHostnameMutex.RUnlock()
	return len(fake.getHostnameArgsForCall)
}

func (fake *FakeExecInterface) GetHostnameCalls(stub func() (string, error)) {
	fake.getHostnameMutex.Lock()
	defer fake.getHostnameMutex.Unlock()
	fake.GetHostnameStub = stub
}

func (fake *FakeExecInterface) GetHostnameReturns(result1 string, result2 error) {
	fake.getHostnameMutex.Lock()
	defer fake.getHostnameMutex.Unlock()
	fake.GetHostnameStub = nil
	fake.getHostnameReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeExecInterface) GetHostnameReturnsOnCall(i int, result1 string, result2 error) {
	fake.getHostnameMutex.Lock()
	defer fake.getHostnameMutex.Unlock()
	fake.GetHostnameStub = nil
	if fake.getHostnameReturnsOnCall == nil {
		fake.getHostnameReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getHostnameReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeExecInterface) GetReleaseInfo(arg1 context.Context) *v1.ReleaseInfo {
	fake.getReleaseInfoMutex.Lock()
	ret, specificReturn := fake.getReleaseInfoReturnsOnCall[len(fake.getReleaseInfoArgsForCall)]
	fake.getReleaseInfoArgsForCall = append(fake.getReleaseInfoArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetReleaseInfoStub
	fakeReturns := fake.getReleaseInfoReturns
	fake.recordInvocation("GetReleaseInfo", []interface{}{arg1})
	fake.getReleaseInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeExecInterface) GetReleaseInfoCallCount() int {
	fake.getReleaseInfoMutex.RLock()
	defer fake.getReleaseInfoMutex.RUnlock()
	return len(fake.getReleaseInfoArgsForCall)
}

func (fake *FakeExecInterface) GetReleaseInfoCalls(stub func(context.Context) *v1.ReleaseInfo) {
	fake.getReleaseInfoMutex.Lock()
	defer fake.getReleaseInfoMutex.Unlock()
	fake.GetReleaseInfoStub = stub
}

func (fake *FakeExecInterface) GetReleaseInfoArgsForCall(i int) context.Context {
	fake.getReleaseInfoMutex.RLock()
	defer fake.getReleaseInfoMutex.RUnlock()
	argsForCall := fake.getReleaseInfoArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeExecInterface) GetReleaseInfoReturns(result1 *v1.ReleaseInfo) {
	fake.getReleaseInfoMutex.Lock()
	defer fake.getReleaseInfoMutex.Unlock()
	fake.GetReleaseInfoStub = nil
	fake.getReleaseInfoReturns = struct {
		result1 *v1.ReleaseInfo
	}{result1}
}

func (fake *FakeExecInterface) GetReleaseInfoReturnsOnCall(i int, result1 *v1.ReleaseInfo) {
	fake.getReleaseInfoMutex.Lock()
	defer fake.getReleaseInfoMutex.Unlock()
	fake.GetReleaseInfoStub = nil
	if fake.getReleaseInfoReturnsOnCall == nil {
		fake.getReleaseInfoReturnsOnCall = make(map[int]struct {
			result1 *v1.ReleaseInfo
		})
	}
	fake.getReleaseInfoReturnsOnCall[i] = struct {
		result1 *v1.ReleaseInfo
	}{result1}
}

func (fake *FakeExecInterface) KillProcess(arg1 int32) error {
	fake.killProcessMutex.Lock()
	ret, specificReturn := fake.killProcessReturnsOnCall[len(fake.killProcessArgsForCall)]
	fake.killProcessArgsForCall = append(fake.killProcessArgsForCall, struct {
		arg1 int32
	}{arg1})
	stub := fake.KillProcessStub
	fakeReturns := fake.killProcessReturns
	fake.recordInvocation("KillProcess", []interface{}{arg1})
	fake.killProcessMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeExecInterface) KillProcessCallCount() int {
	fake.killProcessMutex.RLock()
	defer fake.killProcessMutex.RUnlock()
	return len(fake.killProcessArgsForCall)
}

func (fake *FakeExecInterface) KillProcessCalls(stub func(int32) error) {
	fake.killProcessMutex.Lock()
	defer fake.killProcessMutex.Unlock()
	fake.KillProcessStub = stub
}

func (fake *FakeExecInterface) KillProcessArgsForCall(i int) int32 {
	fake.killProcessMutex.RLock()
	defer fake.killProcessMutex.RUnlock()
	argsForCall := fake.killProcessArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeExecInterface) KillProcessReturns(result1 error) {
	fake.killProcessMutex.Lock()
	defer fake.killProcessMutex.Unlock()
	fake.KillProcessStub = nil
	fake.killProcessReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeExecInterface) KillProcessReturnsOnCall(i int, result1 error) {
	fake.killProcessMutex.Lock()
	defer fake.killProcessMutex.Unlock()
	fake.KillProcessStub = nil
	if fake.killProcessReturnsOnCall == nil {
		fake.killProcessReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.killProcessReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeExecInterface) RunCmd(arg1 context.Context, arg2 string, arg3 ...string) (*bytes.Buffer, error) {
	fake.runCmdMutex.Lock()
	ret, specificReturn := fake.runCmdReturnsOnCall[len(fake.runCmdArgsForCall)]
	fake.runCmdArgsForCall = append(fake.runCmdArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3})
	stub := fake.RunCmdStub
	fakeReturns := fake.runCmdReturns
	fake.recordInvocation("RunCmd", []interface{}{arg1, arg2, arg3})
	fake.runCmdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeExecInterface) RunCmdCallCount() int {
	fake.runCmdMutex.RLock()
	defer fake.runCmdMutex.RUnlock()
	return len(fake.runCmdArgsForCall)
}

func (fake *FakeExecInterface) RunCmdCalls(stub func(context.Context, string, ...string) (*bytes.Buffer, error)) {
	fake.runCmdMutex.Lock()
	defer fake.runCmdMutex.Unlock()
	fake.RunCmdStub = stub
}

func (fake *FakeExecInterface) RunCmdArgsForCall(i int) (context.Context, string, []string) {
	fake.runCmdMutex.RLock()
	defer fake.runCmdMutex.RUnlock()
	argsForCall := fake.runCmdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeExecInterface) RunCmdReturns(result1 *bytes.Buffer, result2 error) {
	fake.runCmdMutex.Lock()
	defer fake.runCmdMutex.Unlock()
	fake.RunCmdStub = nil
	fake.runCmdReturns = struct {
		result1 *bytes.Buffer
		result2 error
	}{result1, result2}
}

func (fake *FakeExecInterface) RunCmdReturnsOnCall(i int, result1 *bytes.Buffer, result2 error) {
	fake.runCmdMutex.Lock()
	defer fake.runCmdMutex.Unlock()
	fake.RunCmdStub = nil
	if fake.runCmdReturnsOnCall == nil {
		fake.runCmdReturnsOnCall = make(map[int]struct {
			result1 *bytes.Buffer
			result2 error
		})
	}
	fake.runCmdReturnsOnCall[i] = struct {
		result1 *bytes.Buffer
		result2 error
	}{result1, result2}
}

func (fake *FakeExecInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.findExecutableMutex.RLock()
	defer fake.findExecutableMutex.RUnlock()
	fake.getHostIDMutex.RLock()
	defer fake.getHostIDMutex.RUnlock()
	fake.getHostnameMutex.RLock()
	defer fake.getHostnameMutex.RUnlock()
	fake.getReleaseInfoMutex.RLock()
	defer fake.getReleaseInfoMutex.RUnlock()
	fake.killProcessMutex.RLock()
	defer fake.killProcessMutex.RUnlock()
	fake.runCmdMutex.RLock()
	defer fake.runCmdMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeExecInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ exec.ExecInterface = new(FakeExecInterface)
