// Copyright (c) F5, Inc.
//
// This source code is licensed under the Apache License, Version 2.0 license found in the
// LICENSE file in the root directory of this source tree.
package config

import (
	"strings"
)

const (
	ClientRootKey                               = "client"
	AllowedDirectoriesKey                       = "allowed_directories"
	ConfigPathKey                               = "path"
	CommandRootKey                              = "command"
	AuxiliaryCommandRootKey                     = "auxiliary_command"
	DataPlaneConfigRootKey                      = "data_plane_config"
	LabelsRootKey                               = "labels"
	LogLevelRootKey                             = "log"
	CollectorRootKey                            = "collector"
	VersionKey                                  = "version"
	UUIDKey                                     = "uuid"
	FeaturesKey                                 = "features"
	InstanceWatcherMonitoringFrequencyKey       = "watchers_instance_watcher_monitoring_frequency"
	InstanceHealthWatcherMonitoringFrequencyKey = "watchers_instance_health_watcher_monitoring_frequency"
	FileWatcherKey                              = "watchers_file_watcher"
	LibDirPathKey                               = "lib_dir"
	MaxAccessLogFilesKey                        = "max_access_log_files"
)

var (
	// child flags saved as vars to enable easier prefixing.
	GrpcKeepAlive                         = pre(ClientRootKey) + "grpc_keepalive"
	ClientKeepAlivePermitWithoutStreamKey = pre(GrpcKeepAlive) + "permit_without_stream"
	ClientKeepAliveTimeKey                = pre(GrpcKeepAlive) + "time"
	ClientKeepAliveTimeoutKey             = pre(GrpcKeepAlive) + "timeout"

	ClientHTTPTimeoutKey                   = pre(ClientRootKey) + "http_timeout"
	ClientGRPCMaxMessageSendSizeKey        = pre(ClientRootKey) + "grpc_max_message_send_size"
	ClientGRPCMaxMessageReceiveSizeKey     = pre(ClientRootKey) + "grpc_max_message_receive_size"
	ClientGRPCMaxMessageSizeKey            = pre(ClientRootKey) + "grpc_max_message_size"
	ClientGRPCMaxFileSizeKey               = pre(ClientRootKey) + "grpc_max_file_size"
	ClientGRPCFileChunkSizeKey             = pre(ClientRootKey) + "grpc_file_chunk_size"
	ClientGRPCMaxParallelFileOperationsKey = pre(ClientRootKey) + "grpc_max_parallel_file_operations"

	ClientBackoffInitialIntervalKey     = pre(ClientRootKey) + "backoff_initial_interval"
	ClientBackoffMaxIntervalKey         = pre(ClientRootKey) + "backoff_max_interval"
	ClientBackoffMaxElapsedTimeKey      = pre(ClientRootKey) + "backoff_max_elapsed_time"
	ClientBackoffRandomizationFactorKey = pre(ClientRootKey) + "backoff_randomization_factor"
	ClientBackoffMultiplierKey          = pre(ClientRootKey) + "backoff_multiplier"

	CollectorConfigPathKey                      = pre(CollectorRootKey) + "config_path"
	CollectorAdditionalConfigPathsKey           = pre(CollectorRootKey) + "additional_config_paths"
	CollectorExportersKey                       = pre(CollectorRootKey) + "exporters"
	CollectorDebugExporterKey                   = pre(CollectorExportersKey) + "debug"
	CollectorPrometheusExporterKey              = pre(CollectorExportersKey) + "prometheus"
	CollectorPrometheusExporterServerHostKey    = pre(CollectorPrometheusExporterKey) + "server_host"
	CollectorPrometheusExporterServerPortKey    = pre(CollectorPrometheusExporterKey) + "server_port"
	CollectorPrometheusExporterTLSKey           = pre(CollectorPrometheusExporterKey) + "tls"
	CollectorPrometheusExporterTLSCertKey       = pre(CollectorPrometheusExporterTLSKey) + "cert"
	CollectorPrometheusExporterTLSKeyKey        = pre(CollectorPrometheusExporterTLSKey) + "key"
	CollectorPrometheusExporterTLSCaKey         = pre(CollectorPrometheusExporterTLSKey) + "ca"
	CollectorPrometheusExporterTLSSkipVerifyKey = pre(CollectorPrometheusExporterTLSKey) + "skip_verify"
	CollectorPrometheusExporterTLSServerNameKey = pre(CollectorPrometheusExporterTLSKey) + "server_name"
	CollectorOtlpExportersKey                   = pre(CollectorExportersKey) + "otlp"
	CollectorProcessorsKey                      = pre(CollectorRootKey) + "processors"
	CollectorExtensionsKey                      = pre(CollectorRootKey) + "extensions"
	CollectorExtensionsHealthKey                = pre(CollectorExtensionsKey) + "health"
	CollectorExtensionsHealthServerHostKey      = pre(CollectorExtensionsHealthKey) + "server_host"
	CollectorExtensionsHealthServerPortKey      = pre(CollectorExtensionsHealthKey) + "server_port"
	CollectorExtensionsHealthPathKey            = pre(CollectorExtensionsHealthKey) + "path"
	CollectorExtensionsHealthTLSKey             = pre(CollectorExtensionsHealthKey) + "tls"
	CollectorExtensionsHealthTLSCaKey           = pre(CollectorExtensionsHealthTLSKey) + "ca"
	CollectorExtensionsHealthTLSCertKey         = pre(CollectorExtensionsHealthTLSKey) + "cert"
	CollectorExtensionsHealthTLSKeyKey          = pre(CollectorExtensionsHealthTLSKey) + "key"
	CollectorExtensionsHealthTLSServerNameKey   = pre(CollectorExtensionsHealthTLSKey) + "server_name"
	CollectorExtensionsHealthTLSSkipVerifyKey   = pre(CollectorExtensionsHealthTLSKey) + "skip_verify"
	CollectorExtensionsHeadersSetterKey         = pre(CollectorExtensionsKey) + "headers_setter"
	CollectorPipelinesKey                       = pre(CollectorRootKey) + "pipelines"
	CollectorMetricsPipelinesKey                = pre(CollectorPipelinesKey) + "metrics"
	CollectorLogsPipelinesKey                   = pre(CollectorPipelinesKey) + "logs"
	CollectorReceiversKey                       = pre(CollectorRootKey) + "receivers"
	CollectorLogKey                             = pre(CollectorRootKey) + "log"
	CollectorLogLevelKey                        = pre(CollectorLogKey) + "level"
	CollectorLogPathKey                         = pre(CollectorLogKey) + "path"

	CommandAuthKey                     = pre(CommandRootKey) + "auth"
	CommandAuthTokenKey                = pre(CommandAuthKey) + "token"
	CommandAuthTokenPathKey            = pre(CommandAuthKey) + "tokenpath"
	CommandServerHostKey               = pre(CommandServerKey) + "host"
	CommandServerKey                   = pre(CommandRootKey) + "server"
	CommandServerPortKey               = pre(CommandServerKey) + "port"
	CommandServerTypeKey               = pre(CommandServerKey) + "type"
	CommandTLSKey                      = pre(CommandRootKey) + "tls"
	CommandTLSCaKey                    = pre(CommandTLSKey) + "ca"
	CommandTLSCertKey                  = pre(CommandTLSKey) + "cert"
	CommandTLSKeyKey                   = pre(CommandTLSKey) + "key"
	CommandTLSServerNameKey            = pre(CommandTLSKey) + "server_name"
	CommandTLSSkipVerifyKey            = pre(CommandTLSKey) + "skip_verify"
	CommandServerProxyTimeoutKey       = pre(CommandServerKey) + "proxy_timeout"
	CommandServerProxyURLKey           = pre(CommandServerKey) + "proxy_url"
	CommandServerProxyUsernameKey      = pre(CommandServerKey) + "proxy_username"
	CommandServerProxyPasswordKey      = pre(CommandServerKey) + "proxy_password"
	CommandServerProxyNoProxyKey       = pre(CommandServerKey) + "proxy_no_proxy"
	CommandServerProxyTokenKey         = pre(CommandServerKey) + "proxy_token"
	CommandServerProxyAuthMethodKey    = pre(CommandServerKey) + "proxy_auth_method"
	CommandServerProxyTLSCertKey       = pre(CommandServerKey) + "proxy_tls_cert"
	CommandServerProxyTLSKeyKey        = pre(CommandServerKey) + "proxy_tls_key"
	CommandServerProxyTLSCaKey         = pre(CommandServerKey) + "proxy_tls_ca"
	CommandServerProxyTLSSkipVerifyKey = pre(CommandServerKey) + "proxy_tls_skip_verify"
	CommandServerProxyTLSServerNameKey = pre(CommandServerKey) + "proxy_tls_server_name"

	AuxiliaryCommandAuthKey          = pre(AuxiliaryCommandRootKey) + "auth"
	AuxiliaryCommandAuthTokenKey     = pre(AuxiliaryCommandAuthKey) + "token"
	AuxiliaryCommandAuthTokenPathKey = pre(AuxiliaryCommandAuthKey) + "tokenpath"
	AuxiliaryCommandServerHostKey    = pre(AuxiliaryCommandServerKey) + "host"
	AuxiliaryCommandServerKey        = pre(AuxiliaryCommandRootKey) + "server"
	AuxiliaryCommandServerPortKey    = pre(AuxiliaryCommandServerKey) + "port"
	AuxiliaryCommandServerTypeKey    = pre(AuxiliaryCommandServerKey) + "type"
	AuxiliaryCommandTLSKey           = pre(AuxiliaryCommandRootKey) + "tls"
	AuxiliaryCommandTLSCaKey         = pre(AuxiliaryCommandTLSKey) + "ca"
	AuxiliaryCommandTLSCertKey       = pre(AuxiliaryCommandTLSKey) + "cert"
	AuxiliaryCommandTLSKeyKey        = pre(AuxiliaryCommandTLSKey) + "key"
	AuxiliaryCommandTLSServerNameKey = pre(AuxiliaryCommandTLSKey) + "server_name"
	AuxiliaryCommandTLSSkipVerifyKey = pre(AuxiliaryCommandTLSKey) + "skip_verify"

	LogLevelKey = pre(LogLevelRootKey) + "level"
	LogPathKey  = pre(LogLevelRootKey) + "path"

	NginxReloadMonitoringPeriodKey           = pre(DataPlaneConfigRootKey, "nginx") + "reload_monitoring_period"
	NginxTreatWarningsAsErrorsKey            = pre(DataPlaneConfigRootKey, "nginx") + "treat_warnings_as_errors"
	NginxReloadBackoffKey                    = pre(DataPlaneConfigRootKey, "nginx") + "reload_backoff"
	NginxReloadBackoffInitialIntervalKey     = pre(NginxReloadBackoffKey) + "initial_interval"
	NginxReloadBackoffMaxIntervalKey         = pre(NginxReloadBackoffKey) + "max_interval"
	NginxReloadBackoffMaxElapsedTimeKey      = pre(NginxReloadBackoffKey) + "max_elapsed_time"
	NginxReloadBackoffRandomizationFactorKey = pre(NginxReloadBackoffKey) + "randomization_factor"
	NginxReloadBackoffMultiplierKey          = pre(NginxReloadBackoffKey) + "multiplier"
	NginxExcludeLogsKey                      = pre(DataPlaneConfigRootKey, "nginx") + "exclude_logs"
	NginxApiTlsCa                            = pre(DataPlaneConfigRootKey, "nginx") + "api_tls_ca"

	SyslogServerPort = pre("syslog_server") + "port"

	FileWatcherMonitoringFrequencyKey = pre(FileWatcherKey) + "monitoring_frequency"
	NginxExcludeFilesKey              = pre(FileWatcherKey) + "exclude_files"
)

func pre(prefixes ...string) string {
	joined := strings.Join(prefixes, KeyDelimiter)
	return joined + KeyDelimiter
}
