name: Sync Secrets from Azure Key Vault
author: s.breen
description: az-sync
inputs:
  keyvault:
    description: 'Azure Key Vault name'
    required: true
  secrets-filter:
    description: 'Filter for secrets to sync (comma-separated patterns)'
    required: true
    default: '*'
runs:
  using: "composite"
  steps:
    - name: Azure login
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ secrets.AZ_KEYVAULT_CLIENT_ID }}
        tenant-id: ${{ secrets.AZ_KEYVAULT_TENANT_ID }}
        subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}

    - name: Sync
      shell: bash
      run: |
        old_IFS=$IFS
        IFS=',' read -r -a array <<< "${{ inputs.secrets-filter }}"
          for pattern in "${array[@]}"; do
            echo "Processing pattern: $pattern"
            for secret_name in $(az keyvault secret list --vault-name ${{ inputs.keyvault }} --query "[?contains(name, '$pattern')].name" -o tsv); do
              echo "Sync secret: env.$secret_name"
              secret_value=$(az keyvault secret show --name "$secret_name" --vault-name ${{ inputs.keyvault }} --query value -o tsv)
              echo "::add-mask::$secret_value"
              echo "$secret_name=$secret_value" >> $GITHUB_ENV
            done
          done
        IFS=$old_IFS

    - name: Azure logout
      shell: bash
      run: |
        az logout
