name: Sync Secrets from Azure Key Vault
author: s.breen
description: az-sync
inputs:
  az_client_id:
    description: 'Azure Client ID'
    required: true
  az_tenant_id:
    description: 'Azure Tenant ID'
    required: true
  az_subscription_id:
    description: 'Azure Subscription ID'
    required: true
  keyvault:
    description: 'Azure Key Vault name'
    required: true
  secrets-filter:
    description: 'Filter for secrets to sync (comma-separated patterns)'
    required: true
    default: '*'
runs:
  using: "composite"
  steps:
    - name: Azure login
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ inputs.az_client_id }}
        tenant-id: ${{ inputs.az_tenant_id }}
        subscription-id: ${{ inputs.az_subscription_id }}

    - name: Sync
      shell: bash
      run: |
        old_IFS=$IFS
        IFS=',' read -r -a array <<< "${{ inputs.secrets-filter }}"
          for pattern in "${array[@]}"; do
            echo "Processing pattern: $pattern"
            for secret_name in $(az keyvault secret list --vault-name ${{ inputs.keyvault }} --query "[?contains(name, '$pattern')].name" -o tsv); do
              echo "Sync secret: env.$secret_name"
              secret_value=$(az keyvault secret show --only-show-errors --name "$secret_name" --vault-name ${{ inputs.keyvault }} --query value -o tsv 2>&1)
              echo "::add-mask::$(echo "$secret_value" | sed ':a;N;$!ba;s/%/%25/g' | sed ':a;N;$!ba;s/\r/%0D/g' | sed ':a;N;$!ba;s/\n/%0A/g')"
              echo "$secret_name=$secret_value" >> $GITHUB_ENV
            done
          done
        IFS=$old_IFS

    - name: Azure logout
      shell: bash
      run: |
        az logout
