[build]
  command = "hugo --gc -b $DEPLOY_PRIME_URL/nginx-app-protect-dos"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.91.1"

[context.production]
  command = "hugo --gc -e production"

[context.docs-development]
  command = "hugo --gc -e development"

[context.docs-staging]
  command = "hugo --gc -e staging"

[context.deploy-preview]
  command = "hugo --gc -b $DEPLOY_PRIME_URL/nginx-agent"
  publish = "public"

[context.branch-deploy]
  command = "hugo --gc -b $DEPLOY_PRIME_URL/nginx-agent"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://docs.nginx.com"

[[redirects]]
  from = "/"
  to = "/nginx-agent/"
  status = 301
  force = true

[[redirects]]
  from = "*"
  to = "/404.html"
  status = 404