version: '3.9'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  victoriametrics_data: {}

services:
  otel-collector:
    image: otel/opentelemetry-collector
    container_name: collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP/2 gRPC receiver
      - "4318:4318"   # OTLP/2 http receiver
      - "55679:55679" # zpages extension
      - "8889:8889"   # prometheus exporter
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--log.level=debug'
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - otel-collector

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    volumes:
      - victoriametrics_data:/victoria-metrics-data
    command:
      - '--graphiteListenAddr=:2003'
      - '--opentsdbListenAddr=:4242'
      - '--httpListenAddr=:8428'
      - '--retentionPeriod=12'
    ports:
      - "8428:8428"
    networks:
      - monitoring
    depends_on:
      - prometheus
