global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']  # Ensure this matches the OTel Collector's Prometheus metrics port

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
