name: "Dependency Review"
on:
  pull_request:
    branches:
      - main
      - release-*
      - dev-v2
  merge_group:

concurrency:
  group: ${{ github.ref_name }}-deps-review
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-24.04
    permissions:
      contents: read # for actions/checkout
      pull-requests: write # for actions/dependency-review-action to post comments
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Dependency Review"
        uses: actions/dependency-review-action@5bbc3ba658137598168acb2ab73b21c432dd411b # v4.2.5
        with:
          config-file: "nginx/k8s-common/dependency-review-config.yml@main"
