name: Label Pull Requests

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  label-pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: release-drafter/release-drafter/autolabeler@c2e2804cc59f45f57076a99af580d0fedb697927 # v7.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
